### ISSUE TITLE
Support for NAU8325 chip?

### ISSUE THREAD

**Issue by koendeschacht** [OpenNuvoton/NuMaker-mbed-Audio#1]
Hi,

I have been experimenting with the NAU8325 chip but have been unable to get it working. Any chance on an implementation for this chip?

Thanks!

**Comment by cyliangtw** [comment]
This repo is audio lib with NAU8822/88L25 built-on several Mbed NuMaker boards for Mbed audio example https://os.mbed.com/teams/Nuvoton/code/NuMaker-mbed-AudioPlayback-example/

What's your target board, is xxx-M487 ?

**Comment by koendeschacht** [comment]
Thanks for the quick response! I'm using the demo board NL-NAU8325, controlled by an ESP-32.

**Comment by cyliangtw** [comment]
Your issue is NAU8325 manipulation, not this repo Mbed audio lib issue.
Please contact the technical support https://www.nuvoton.com/support/technical-support/form/
